### PR TITLE
Add sync option to mobx-persist.

### PR DESCRIPTION
**Pull request by snowl**
This will allow users to automatically sync their data between tabs whenever localStorage is updated.

### CODE REVIEW

**Comment by pinqy520** [comment]
@snowl Hi, thank you for this PR, I think it is great to automatically sync data between tabs, but i don't think it should be a part of `mobx-persist`. the cross-tab sync function should be a plugin just like [`redux-persist-crosstab`](https://github.com/rt2zz/redux-persist-crosstab).

I will provide a new `rehydrate` api, and you can call it when the `localStorage` is updated.

**Comment by yordis** [comment]
@pinqy520 I agree with you specially for the `window` (browser stuff) checking

but how can we get this today? how would that plugin look like?

**Comment by pinqy520** [comment]
@yordis I just publish a new version 0.4.0, which provides `rehydrate` api.

``` javascript
const result = hydrate('some', someStore, initialState)
const rehydrate = result.rehydrate
result.then(() => console.log('some hydrated'))

window.addEventListener("storage", rehydrate)
```

**Comment by yordis** [comment]
@pinqy520 is this valid or should be close?

**Pull request closed without merging**
