### PR TITLE
adds API docs

### PR DESCRIPTION
**Pull request by datwheat**
just wanted to help out and make this lib more friendly 👍

### CODE REVIEW

**Comment by pinqy520** [comment]
~! Thank you so much ~!. My english is not good, so this is very helpful for me.

**Comment by pinqy520** [comment]
Hi, i have merged this pr, and I changed some description of `create(config)`.

I implemented a lightweight [localForage](https://github.com/localForage/localForage)-style storage API for web using localStorage, so the `config.storage` should also use the localForage-style API like what AsyncStorage does, and it can not be set to `localStorage` which is not using the localForage-style API.

**Comment by datwheat** [comment]
Ah okay. It wasn't clear that you were referring to that and not just misspelling localStorage, so it would be great if you clarified that in the README

**Comment by datwheat** [comment]
```
const hydrate = create({
    storage: localForage,   // or AsyncStorage in react-native.
                            // default: localStorage <- this is confusing because the example uses localForage and you said that localStorage isn't a viable option
    jsonify: false  // if you use AsyncStorage, here shoud be true
                    // default: true
})
```

and also in the create description you should remove the localStorage option if that's not usable

**Comment by pinqy520** [comment]
I add the support for `localStorage`, and i think it may be better for users. 

``` javascript
if (typeof localStorage !== 'undefined' && localStorage === storage) storage = Storage
```

**Pull request merged**
